apiVersion: apps/v1
kind: Deployment
metadata:
  name: darknet-metal
spec:
  selector:
    matchLabels:
      app: darknet-metal
  replicas: 1
  template:
    metadata:
      labels:
        app: darknet-metal
    spec:
      containers:
        - name: darknet-metal
          image: darknet-gpu:latest
          command: ["/bin/sh", "-c"]
          args:
            - echo starting;
              sleep 1000000;
              echo done;
          imagePullPolicy: Always
          volumeMounts:
          - name: darknet
            mountPath: "/mnt/darknet"
      volumes:
      - name: darknet
        persistentVolumeClaim:
          claimName: darknet-gpu-volume            
      restartPolicy: Always
