apiVersion: v1
kind: ConfigMap
metadata:
  name: cam-sim-conf-1
data:
  BOOTSTRAP_SERVER: kafka-cluster-kafka-bootstrap:9092
#  BOOTSTRAP_SERVER: kafka-cluster-kafka-bootstrap-sbergste-opencv2.apps.ocp4.stormshift.coe.muc.redhat.com:443
#  SECURITY_PROTOCOL: SSL
#  SSL_CAFILE: /mnt/kafka-ca-cert/kafka-ca.crt
  CAMID: '1'
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cam-sim-1
  labels:
    app: cam-sim
spec:
  selector:
    matchLabels:
      app: cam-sim-1
  replicas: 1
  template:
    metadata:
      labels:
        app: cam-sim-1
    spec:
      containers:
        - name: cam-sim
          image: cam-sim:latest
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: cam-sim-conf-1
            - configMapRef:
                name: kafka-ca-cert
          volumeMounts:
            - name: kafka-ca-cert-volume
              mountPath: /mnt/kafka-ca-cert
      volumes:
        - name: kafka-ca-cert-volume
          configMap:
            name: kafka-ca-cert
            defaultMode: 420
      restartPolicy: Always
