apiVersion: v1
kind: ConfigMap
metadata:
  name: image-processor-conf
data:
  YOLO_CLASS_FILE: classes.txt
  CE_ACTION_TYPE: "manuela.image-processor.action"
  CE_ACTION_SOURCE: "manuela/eventing/image-processor"
  KN_BROKER_URL: "http://broker-ingress.knative-eventing.svc.cluster.local/sbergste-knative/default"
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: image-processor
  labels:
    app: visual-inspection
    app.kubernetes.io/part-of: visual-inspection
    app.openshift.io/runtime: python
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/target: '100'
        autoscaling.knative.dev/targetUtilizationPercentage: '70'
        autoscaling.knative.dev/window: 60s
      labels:
        app.kubernetes.io/component: image-processor
        app.kubernetes.io/instance: image-processor
        app.kubernetes.io/part-of: strimzi-manu-vi
        app.openshift.io/runtime: python
        app.openshift.io/runtime-namespace: manuela-visual-inspection
        app.openshift.io/runtime-version: latest
    spec:
      containerConcurrency: 0
      containers:
        - name: image-processor
          image: image-registry.openshift-image-registry.svc:5000/manuela-visual-inspection/image-processor:latest
          imagePullPolicy: Always
          envFrom:
          - configMapRef:
              name: image-processor-conf
          resources: {}
      enableServiceLinks: false
      timeoutSeconds: 300
  traffic:
    - latestRevision: true
      percent: 100