apiVersion: sources.knative.dev/v1beta1
kind: KafkaSource
metadata:
  name: image-processor-kafka-source
spec:
  bootstrapServers:
    - manu-vi-kafka-bootstrap.manuela-visual-inspection.svc.cluster.local:9091
    - manu-vi-kafka-bootstrap.manuela-visual-inspection.svc.cluster.local:9092
    - manu-vi-kafka-bootstrap.manuela-visual-inspection.svc.cluster.local:9093
  consumerGroup: image-processor-kafka-source
  sink:
    ref:
      apiVersion: eventing.knative.dev/v1
      kind: Broker
      name: default
  topics:
    - visual-inspection-images